Feature/#15
a-component/datagrid pull request #19
Opened 2021-11-26 03:43 UTC by ybw903

## issue

default cell doesn't change a value and clicking

## solved

* when click the cell. it could change a cell value
* When click the cell, you can call the callback functions.
* If you want to switch on editing feature. you can do that whatever you want

 **- after issue**
<br />
<img src ="https://user-images.githubusercontent.com/52450447/143409039-9eb4154f-081d-4788-90af-db3fb90c7b6a.gif" width="300" height="400"  />

2021-11-26 04:50 UTC, thomasJang commented
When the cell changes to an edited state, the height of the column increases.
If you change the style of Input, it will be possible to solve it.

2021-11-26 04:59 UTC, thomasJang reviewed
Well done,
Eddy will do an additional review.

2021-11-26 04:59 UTC, thomasJang commented on src/components/body/BodyTableRow.tsx
> +              defaultValue ={item}
blur이벤트가 발생했을 때만 에디트 처리가 되고 있습니다.
ESC키입력시엔 에디팅 상태가 취소되어야 하겠고 필요에 따라서 Enter키로도 수정이 가능 하면 좋겠습니다.

2021-11-26 04:59 UTC, thomasJang commented on src/components/body/BodyTableRow.tsx
> +      nextData[rowIndex]["value"][key] = evt.currentTarget.value;
데이터 변경후에 사용자에게 데이터변경을 알려주는 이벤트 호출이 필요하겠습니다.
내부의 데이터 변경만 이루어 지고 데이터의 주인인 사용자는 이 변경사항을 알수 없는 상태 입니다.

2021-11-26 04:59 UTC, thomasJang commented on src/components/body/BodyTableRow.tsx
> +  const onBlur:React.FocusEventHandler<HTMLInputElement> = (evt) => {
현재는 블러 이벤트가 데이터 조작까지 모두 해결하는 형태 입니다.

블러이벤트말고 나중에 Keydown이벤트 발생시도 데이터 조작을 해야 하는 상황으로 바뀌게 되면 데이터 조작을 처리하는 함수를 따로 만들 필요가 있습니다.

2021-11-26 05:34 UTC, Eddy-Jeon requested changes
컴포넌트 내에서 함수를 사용하는 경우 useCallback을 활용해서 작성해주세요.

2021-11-26 05:34 UTC, Eddy-Jeon commented on src/components/body/BodyTableRow.tsx
> +    setEditingPosition({ ...editingPosition, col: colIdx, row: rowIdx });
If you want to update state with previous state, use functional-updates.
ref: https://ko.reactjs.org/docs/hooks-reference.html#functional-updates

2021-11-26 05:34 UTC, Eddy-Jeon commented on src/components/body/BodyTableRow.tsx
> +      setEditingPosition({...setEditingPosition, col: -1, row: -1});
If you want to update state with previous state, use functional-updates.
ref: https://ko.reactjs.org/docs/hooks-reference.html#functional-updates

2021-11-26 05:34 UTC, Eddy-Jeon commented on src/components/body/BodyTableRow.tsx
> +    const colIdx = evt.currentTarget.dataset.col
valaue와 colIdx 정보는 dataset보다는
customClickHandler 함수의 매개변수로 받는 걸로 수정해주세요.

ref: https://developer.mozilla.org/ko/docs/Learn/HTML/Howto/Use_data_attributes#%EB%AC%B8%EC%A0%9C%EC%A0%90

2021-11-26 05:34 UTC, Eddy-Jeon commented on src/components/body/BodyTableRow.tsx
> +              id = {ci.toString()}
```suggestion
              id = {String(ci)}
```

2021-11-26 05:34 UTC, Eddy-Jeon commented on src/components/body/BodyTableRow.tsx
> +          onClick={customClickHandler}
customClickHandler에 item과 colIndex 정보를 넘겨주는 inline 함수로 변경해주세요.

2021-11-26 05:34 UTC, Eddy-Jeon commented on src/@interface.ts
> +  setEditOptions?: boolean;
```suggestion
  enableEditCell?: boolean;
```

2021-11-26 07:55 UTC, ybw903 commented
> ## issue
> default cell doesn't change a value and clicking
> 
> ## solved
> * when click the cell. it could change a cell value
> * When click the cell, you can call the callback functions.
> * If you want to switch on editing feature. you can do that whatever you want
> 
> **- after issue** <img alt="" width="300" height="400" src="https://user-images.githubusercontent.com/52450447/143409039-9eb4154f-081d-4788-90af-db3fb90c7b6a.gif">

2021-11-27 06:19 UTC, Eddy-Jeon approved these changes

2021-11-27 06:19 UTC, merged